import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
    DynamicContextProvider,
    StarknetWalletConnectors,
    ArgentXWalletConnectorType,
} from "../lib/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <DynamicContextProvider
            settings={{
                //initialAuthenticationMode: "connect-only",
                environmentId: '',
                walletConnectors: [StarknetWalletConnectors],
            }}
        >
            <body className={inter.className}>{children}</body>
        </DynamicContextProvider>
        </html>
    );
}
